import type { XYPosition } from "@xyflow/react";

export type SessionNodeKind = "idea" | "ghost" | "critic";
export type SessionEdgeRelation = "branch" | "suggestion" | "constraint";
export type SessionViewMode = "canvas" | "outline";

export type SessionNode = {
  id: string;
  kind: SessionNodeKind;
  content: string;
  note: string;
  position: XYPosition;
};

export type SessionEdge = {
  id: string;
  source: string;
  target: string;
  relation: SessionEdgeRelation;
};

export type BrainstormSession = {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  nodes: SessionNode[];
  edges: SessionEdge[];
};

export type StoredSessionSummary = {
  fileName: string;
  filePath: string;
  title: string;
  updatedAt: string;
  sessionId: string;
  savedAt: string;
};

function nowIso() {
  return new Date().toISOString();
}

function sessionId() {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `session-${crypto.randomUUID()}`;
  }

  return `session-${Date.now()}`;
}

export function createStarterSession(): BrainstormSession {
  const timestamp = nowIso();

  return {
    id: sessionId(),
    title: "New brainstorming session",
    createdAt: timestamp,
    updatedAt: timestamp,
    nodes: [
      {
        id: "node-seed-idea",
        kind: "idea",
        content: "Gamified Habit App",
        note: "This is the user-authored root concept from the README example.",
        position: { x: 0, y: 0 }
      },
      {
        id: "node-seed-ghost",
        kind: "ghost",
        content: "Accountability Circle Mode",
        note: "A translucent adjacent suggestion generated by the Expander agent.",
        position: { x: 280, y: -90 }
      },
      {
        id: "node-seed-critic",
        kind: "critic",
        content: "Yes, but retention may collapse after the novelty wears off.",
        note: "A challenge badge from the Critic agent to avoid shallow consensus.",
        position: { x: 280, y: 130 }
      }
    ],
    edges: [
      {
        id: "edge-seed-ghost",
        source: "node-seed-idea",
        target: "node-seed-ghost",
        relation: "suggestion"
      },
      {
        id: "edge-seed-critic",
        source: "node-seed-idea",
        target: "node-seed-critic",
        relation: "constraint"
      }
    ]
  };
}
